cartopy                   0.22.0          py311hab14417_0    conda-forge
cmcrameri                 1.7                pyhd8ed1ab_0    conda-forge
matplotlib                3.8.0           py311h6eed73b_0    conda-forge
matplotlib-base           3.8.0           py311haff9b01_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
numpy                     1.24.4          py311hc44ba51_0    conda-forge
pandas                    2.1.1           py311hab14417_1    conda-forge
scipy                     1.11.3          py311h16c3c4d_0    conda-forge
xarray                    2023.9.0           pyhd8ed1ab_0    conda-forge
